---
title: "Tables"
author: "Michał Bojanowski"
date: '`r Sys.Date()`'
output:
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    toc: yes
  bookdown::html_document2:
    keep_md: yes
    number_sections: yes
    toc: yes
  html_document:
    keep_md: yes
    number_sections: yes
    toc: yes
  pdf_document:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE, cache=FALSE}
library(lme4)
library(tidyverse)
library(broom)

source("functions.R")

knitr::opts_chunk$set(
  echo = TRUE,
  cache=FALSE
)

set.seed(123)
```


# Tables

Data frame

```{r table-data-frame}
d <- data.frame(
  Variable = LETTERS[1:5],
  num = 1:5,
  ch = letters[1:5],
  f = factor(letters[1:5]),
  logical = as.logical(sample(0:1, 5, replace=TRUE)),
  stringsAsFactors = FALSE
)
d
```



## `knitr::kable()`

```{r knitrtable}
knitr::kable(d, caption = "This is knitr kable table.")
```

See table \@ref(tab:knitrtable).


## `htmlTable`

```{r eval=to_html()}
htmlTable::htmlTable(
  d,
  rnames = FALSE,
  rgroup = c("First group", "Second group"),
  n.rgroup = c(2,3),
  cgroup = c("", paste("Model", 1:2)),
  n.cgroup = c(1, 2, 2),
  caption = "This is made with 'htmlTable'."
)
```

## `Hmisc::latex`

```{r eval=to_pdf(), results='asis'}
dd <- d[,-1]
rownames(dd) <- d$Variable
Hmisc::latex(
  dd, 
  dcolumn=TRUE,
  title = "Title",
  file="", booktabs=TRUE, 
  rgroup = c("First group", "Second group"),
  n.rgroup = c(2,3),
  cgroup = paste("Model", 1:2),
  n.cgroup = c(2, 2),
  assignment = FALSE,
  caption = "This is made with Hmisc::latex."
)
```







## Anytable

```{r, results="asis"}
anytable(
  d,
  rnames = "Variable",
  rgroup = c("First group", "Second group"),
  n.rgroup = c(2,3),
  cgroup = paste("Model", 1:2),
  n.cgroup = c(2, 2),
  label="tableone",
  title = "Some table",
  caption = "This is made with 'anytable'."
)
```


See table \@ref(tab:tableone) for the application of `anytable()`.








# LMER

Modele

```{r lmer-models, cache=TRUE}
mod0 <- lmer(Reaction ~ (1 | Subject), sleepstudy)
mod1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
```

```{r lmer-model-table}
vlabs <- c(
"sd_(Intercept).Subject" = "Subject",
"sd_Days.Subject" = "Days",
"sd_Observation.Residual" = "Residual",
"(Intercept)" = "(Intercept)",
"Days" = "Days"
)
vlabs <- data.frame(
  Variable = vlabs,
  term = names(vlabs),
  stringsAsFactors = FALSE
)

model_table <- 
  full_join(
    tidy(mod0),
    tidy(mod1),
    by=c("term", "group"),
    suffix = c(".1", ".2")
  ) %>%
  gather(col, value, ends_with(".1"), ends_with(".2")) %>%
  extract(col, c("what", "model"), "(.*)\\.([0-9])") %>%
  mutate(
    value = round(value, 3),
    fixed = group == "fixed",
    residual = group == "Residual"
  ) %>%
  filter( what != "statistic", !grepl("^cor_", term) ) %>%
  left_join(vlabs, by="term") %>%
  unite("k", what, model) %>%
  spread(k, value) %>%
  arrange(fixed) %>%
  select(
    Variable,
    Estimate = estimate_1,
    S.E. = std.error_1,
    Estimate = estimate_2,
    S.E. = std.error_2
  )
```

Anytable

```{r anytable-lmer, results="asis"}
  anytable(
    model_table,
    title = "Random effect model",
    rnames = "Variable",
    rgroup = c("Random effects", "Fixed effects"),
    n.rgroup=c(3, 2),
    cgroup = c("Model 1", "Model 2"),
    n.cgroup = c(2, 2),
    label="lmer",
    caption = "lmer models."
  )
```

See \@ref(tab:lmer) for `lmer()` models.


```{r anytable-lmer-latex, results="markup"}
  anytable_md(
    model_table,
    title = "Random effect model",
    rnames = "Variable",
    rgroup = c("Random effects", "Fixed effects"),
    n.rgroup=c(3, 2),
    cgroup = c("Model 1", "Model 2"),
    n.cgroup = c(2, 2),
    label="lmer",
    caption = "lmer models."
  )
```




# Appendix {-}

```{r output}
knitr::opts_knit$get("out.format")
knitr::opts_knit$get("rmarkdown.pandoc.to")
```
